# Test reading of HDF5 example file
# The HDF5 example file is generated by tests/create_example_hdf5.py

import biobabel as bb


def test_read():
    bio = bb.load("tests/samples/example.hdf5")
    assert 'a' in bio.get_participants()
    assert 'b' in bio.get_participants()

    assert 'a_ecg' in [ w['id'] for (w,_) in bio.find() ]

    info, dat = bio.get("a_ecg")
    assert info["sampling_frequency"] == 1000
